//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך.
        /// </summary>
        internal static string ContinuButton {
            get {
                return ResourceManager.GetString("ContinuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי כרטיס אשראי.
        /// </summary>
        internal static string PCICtrl_Header {
            get {
                return ResourceManager.GetString("PCICtrl_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי מוצרים נוספים.
        /// </summary>
        internal static string PMN01_AdditionalProductDetails {
            get {
                return ResourceManager.GetString("PMN01_AdditionalProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המראה.
        /// </summary>
        internal static string PMN01_Flight {
            get {
                return ResourceManager.GetString("PMN01_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי טיסות.
        /// </summary>
        internal static string PMN01_FlightsDetails {
            get {
                return ResourceManager.GetString("PMN01_FlightsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אורחים.
        /// </summary>
        internal static string PMN01_Guests {
            get {
                return ResourceManager.GetString("PMN01_Guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string PMN01_Name {
            get {
                return ResourceManager.GetString("PMN01_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתתף.
        /// </summary>
        internal static string PMN01_Participant {
            get {
                return ResourceManager.GetString("PMN01_Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת משתתפים.
        /// </summary>
        internal static string PMN01_ParticipantsList {
            get {
                return ResourceManager.GetString("PMN01_ParticipantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נוסעים.
        /// </summary>
        internal static string PMN01_Passengers {
            get {
                return ResourceManager.GetString("PMN01_Passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצר.
        /// </summary>
        internal static string PMN01_Product {
            get {
                return ResourceManager.GetString("PMN01_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג דמי רישום.
        /// </summary>
        internal static string PMN01_RegistrationFeesType {
            get {
                return ResourceManager.GetString("PMN01_RegistrationFeesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חדר.
        /// </summary>
        internal static string PMN01_Room {
            get {
                return ResourceManager.GetString("PMN01_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסעה.
        /// </summary>
        internal static string PMN01_Shuttle {
            get {
                return ResourceManager.GetString("PMN01_Shuttle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסעות.
        /// </summary>
        internal static string PMN01_Shuttles {
            get {
                return ResourceManager.GetString("PMN01_Shuttles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ ערך הזמנה.
        /// </summary>
        internal static string PMN01_TotalOrderValue {
            get {
                return ResourceManager.GetString("PMN01_TotalOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתתף.
        /// </summary>
        internal static string PMN01_UnitsNumber {
            get {
                return ResourceManager.GetString("PMN01_UnitsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערך.
        /// </summary>
        internal static string PMN01_Value {
            get {
                return ResourceManager.GetString("PMN01_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת לשליחת חשבונית.
        /// </summary>
        internal static string PMN02_AddressToSendInvoice {
            get {
                return ResourceManager.GetString("PMN02_AddressToSendInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יתרה לתשלום בכרטיס אשראי.
        /// </summary>
        internal static string PMN02_BalanceDue {
            get {
                return ResourceManager.GetString("PMN02_BalanceDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטי כרטיס אשראי לביטחון:.
        /// </summary>
        internal static string PMN02_CardDetailsSecurity {
            get {
                return ResourceManager.GetString("PMN02_CardDetailsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם בעל הכרטיס.
        /// </summary>
        internal static string PMN02_CardholderName {
            get {
                return ResourceManager.GetString("PMN02_CardholderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר כרטיס.
        /// </summary>
        internal static string PMN02_CardNumber {
            get {
                return ResourceManager.GetString("PMN02_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המחאה.
        /// </summary>
        internal static string PMN02_Check {
            get {
                return ResourceManager.GetString("PMN02_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העברה בנקאית.
        /// </summary>
        internal static string PMN02_EFT {
            get {
                return ResourceManager.GetString("PMN02_EFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ת.ז./ ח.פ..
        /// </summary>
        internal static string PMN02_ID {
            get {
                return ResourceManager.GetString("PMN02_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אם ברצונך להפיק חשבונית על שם אחר נא מלא את הפרטים הבאים:.
        /// </summary>
        internal static string PMN02_InvoiceForOtherName {
            get {
                return ResourceManager.GetString("PMN02_InvoiceForOtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string PMN02_Name {
            get {
                return ResourceManager.GetString("PMN02_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אמצעי תשלום.
        /// </summary>
        internal static string PMN02_Payment {
            get {
                return ResourceManager.GetString("PMN02_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתשלום בכרטיס אשראי.
        /// </summary>
        internal static string PMN02_PaymentByCard {
            get {
                return ResourceManager.GetString("PMN02_PaymentByCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לתשלום באמצעים אחרים.
        /// </summary>
        internal static string PMN02_PaymentByOther {
            get {
                return ResourceManager.GetString("PMN02_PaymentByOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חלוקת התשלום בין המשתתפים.
        /// </summary>
        internal static string PMN02_PaymentDistribution {
            get {
                return ResourceManager.GetString("PMN02_PaymentDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר תשלומים.
        /// </summary>
        internal static string PMN02_Payments {
            get {
                return ResourceManager.GetString("PMN02_Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ ערך הזמנה.
        /// </summary>
        internal static string PMN02_TotalOrderValue {
            get {
                return ResourceManager.GetString("PMN02_TotalOrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן יתרה לתשלום.
        /// </summary>
        internal static string PMN02_Update {
            get {
                return ResourceManager.GetString("PMN02_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכנס כתובת מייל תקינה.
        /// </summary>
        internal static string PMN04_EnterCorrectEmail {
            get {
                return ResourceManager.GetString("PMN04_EnterCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבל את מסמכי הרישום במייל.
        /// </summary>
        internal static string PMN04_SendToMail {
            get {
                return ResourceManager.GetString("PMN04_SendToMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שליחת מסמכי הזמנה לדוא&quot;ל.
        /// </summary>
        internal static string PMN04_SendToMail2 {
            get {
                return ResourceManager.GetString("PMN04_SendToMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקבלת מסמכי הזמנה יש להזין את כתובת הדוא&quot;ל הרצויה.
        /// </summary>
        internal static string PMN04_TXTEnterEmail {
            get {
                return ResourceManager.GetString("PMN04_TXTEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תינוקות.
        /// </summary>
        internal static string PRD01_Babies {
            get {
                return ResourceManager.GetString("PRD01_Babies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הערות למלון.
        /// </summary>
        internal static string PRD01_Comments {
            get {
                return ResourceManager.GetString("PRD01_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרכב.
        /// </summary>
        internal static string PRD01_Composition {
            get {
                return ResourceManager.GetString("PRD01_Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מלא.
        /// </summary>
        internal static string PRD01_Full {
            get {
                return ResourceManager.GetString("PRD01_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חדר.
        /// </summary>
        internal static string PRD01_Room {
            get {
                return ResourceManager.GetString("PRD01_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חדר מספר .
        /// </summary>
        internal static string PRD01_RoomNum {
            get {
                return ResourceManager.GetString("PRD01_RoomNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג חדר.
        /// </summary>
        internal static string PRD01_RoomType {
            get {
                return ResourceManager.GetString("PRD01_RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר בסיס אירוח.
        /// </summary>
        internal static string PRD01_SelectBase {
            get {
                return ResourceManager.GetString("PRD01_SelectBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר מלון .
        /// </summary>
        internal static string PRD01_SelectHotel {
            get {
                return ResourceManager.GetString("PRD01_SelectHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר מספר חדרים.
        /// </summary>
        internal static string PRD01_SelectNumRooms {
            get {
                return ResourceManager.GetString("PRD01_SelectNumRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר סוג חדר.
        /// </summary>
        internal static string PRD01_SelectRoomType {
            get {
                return ResourceManager.GetString("PRD01_SelectRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בסיס ארוח.
        /// </summary>
        internal static string PRD02_Base {
            get {
                return ResourceManager.GetString("PRD02_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקה בחירה.
        /// </summary>
        internal static string PRD02_Clear {
            get {
                return ResourceManager.GetString("PRD02_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חדר מספר.
        /// </summary>
        internal static string PRD02_NumRoom {
            get {
                return ResourceManager.GetString("PRD02_NumRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חזור לבחירת מלונות.
        /// </summary>
        internal static string PRD02_Return {
            get {
                return ResourceManager.GetString("PRD02_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך ללא בחירת טיסות.
        /// </summary>
        internal static string PRD03_Continue {
            get {
                return ResourceManager.GetString("PRD03_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המראה.
        /// </summary>
        internal static string PRD03_Flight {
            get {
                return ResourceManager.GetString("PRD03_Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מ.
        /// </summary>
        internal static string PRD03_From {
            get {
                return ResourceManager.GetString("PRD03_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מלא.
        /// </summary>
        internal static string PRD03_Full {
            get {
                return ResourceManager.GetString("PRD03_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נחיתה.
        /// </summary>
        internal static string PRD03_Landing {
            get {
                return ResourceManager.GetString("PRD03_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נותרו.
        /// </summary>
        internal static string PRD03_Left {
            get {
                return ResourceManager.GetString("PRD03_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נותר מקום אחד פנוי בטיסה.
        /// </summary>
        internal static string PRD03_OnePlace {
            get {
                return ResourceManager.GetString("PRD03_OnePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר נוסעים.
        /// </summary>
        internal static string PRD03_PassengersNum {
            get {
                return ResourceManager.GetString("PRD03_PassengersNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר למבוגר.
        /// </summary>
        internal static string PRD03_PriceToAdult {
            get {
                return ResourceManager.GetString("PRD03_PriceToAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נותרו {0} מקומות אחרונים בטיסה.
        /// </summary>
        internal static string PRD03_SumPlace {
            get {
                return ResourceManager.GetString("PRD03_SumPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ל.
        /// </summary>
        internal static string PRD03_To {
            get {
                return ResourceManager.GetString("PRD03_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בשעה.
        /// </summary>
        internal static string PRD04_At {
            get {
                return ResourceManager.GetString("PRD04_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקה.
        /// </summary>
        internal static string PRD04_Clear {
            get {
                return ResourceManager.GetString("PRD04_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מ.
        /// </summary>
        internal static string PRD04_From {
            get {
                return ResourceManager.GetString("PRD04_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חזור לבחירת טיסות.
        /// </summary>
        internal static string PRD04_ReturnToFlight {
            get {
                return ResourceManager.GetString("PRD04_ReturnToFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        internal static string PRD04_Select {
            get {
                return ResourceManager.GetString("PRD04_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ל.
        /// </summary>
        internal static string PRD04_To {
            get {
                return ResourceManager.GetString("PRD04_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ עלות טיסות.
        /// </summary>
        internal static string PRD04_TotalePrice {
            get {
                return ResourceManager.GetString("PRD04_TotalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצר נוסף.
        /// </summary>
        internal static string PRD05_AnotherProd {
            get {
                return ResourceManager.GetString("PRD05_AnotherProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אטרקציות.
        /// </summary>
        internal static string PRD05_Attractions {
            get {
                return ResourceManager.GetString("PRD05_Attractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר כרטיס.
        /// </summary>
        internal static string PRD05_CardPrice {
            get {
                return ResourceManager.GetString("PRD05_CardPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כרטיסים.
        /// </summary>
        internal static string PRD05_Cards {
            get {
                return ResourceManager.GetString("PRD05_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כרטיסים למבוגר.
        /// </summary>
        internal static string PRD05_CardsToAdult {
            get {
                return ResourceManager.GetString("PRD05_CardsToAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כרטיסים לילד.
        /// </summary>
        internal static string PRD05_cardsToChild {
            get {
                return ResourceManager.GetString("PRD05_cardsToChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקה בחירה.
        /// </summary>
        internal static string PRD05_Clear {
            get {
                return ResourceManager.GetString("PRD05_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר למבוגר.
        /// </summary>
        internal static string PRD05_PriceToAdults {
            get {
                return ResourceManager.GetString("PRD05_PriceToAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר לילד.
        /// </summary>
        internal static string PRD05_PriceToChild {
            get {
                return ResourceManager.GetString("PRD05_PriceToChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצר.
        /// </summary>
        internal static string PRD05_Product {
            get {
                return ResourceManager.GetString("PRD05_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        internal static string PRD05_Select {
            get {
                return ResourceManager.GetString("PRD05_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירת אורחים לאטרקציות.
        /// </summary>
        internal static string PRD05_SelectGuestsToAtractions {
            get {
                return ResourceManager.GetString("PRD05_SelectGuestsToAtractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכרטיסים אזלו.
        /// </summary>
        internal static string PRD05_SoldOut {
            get {
                return ResourceManager.GetString("PRD05_SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסעות חזור.
        /// </summary>
        internal static string PRD09_BackShuttles {
            get {
                return ResourceManager.GetString("PRD09_BackShuttles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקה בחירה.
        /// </summary>
        internal static string PRD09_ClearSelection {
            get {
                return ResourceManager.GetString("PRD09_ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסעות הלוך.
        /// </summary>
        internal static string PRD09_HalochShuttles {
            get {
                return ResourceManager.GetString("PRD09_HalochShuttles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר נוסעים.
        /// </summary>
        internal static string PRD09_PassengerNum {
            get {
                return ResourceManager.GetString("PRD09_PassengerNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר.
        /// </summary>
        internal static string PRD09_Price {
            get {
                return ResourceManager.GetString("PRD09_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        internal static string PRD09_Select {
            get {
                return ResourceManager.GetString("PRD09_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירת נוסעים להסעות.
        /// </summary>
        internal static string PRD09_SelectPassengers {
            get {
                return ResourceManager.GetString("PRD09_SelectPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסעות מאילת.
        /// </summary>
        internal static string PRD09_ShuttleFromEilat {
            get {
                return ResourceManager.GetString("PRD09_ShuttleFromEilat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הסעות לאילת.
        /// </summary>
        internal static string PRD09_ShuttleToEilat {
            get {
                return ResourceManager.GetString("PRD09_ShuttleToEilat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כמות.
        /// </summary>
        internal static string PRD13_Amount {
            get {
                return ResourceManager.GetString("PRD13_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כמות למבוגר.
        /// </summary>
        internal static string PRD13_AmountAdult {
            get {
                return ResourceManager.GetString("PRD13_AmountAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כמות לילד.
        /// </summary>
        internal static string PRD13_AmountChild {
            get {
                return ResourceManager.GetString("PRD13_AmountChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקה בחירה.
        /// </summary>
        internal static string PRD13_Clear {
            get {
                return ResourceManager.GetString("PRD13_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PRD13_Hotel {
            get {
                return ResourceManager.GetString("PRD13_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארוחת צהרים במלון {0}.
        /// </summary>
        internal static string PRD13_Lunch {
            get {
                return ResourceManager.GetString("PRD13_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארוחת צהרים במלון.
        /// </summary>
        internal static string PRD13_MealAtHotel {
            get {
                return ResourceManager.GetString("PRD13_MealAtHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארוחות לבחירה.
        /// </summary>
        internal static string PRD13_MealsToSelect {
            get {
                return ResourceManager.GetString("PRD13_MealsToSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר.
        /// </summary>
        internal static string PRD13_Price {
            get {
                return ResourceManager.GetString("PRD13_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר למבוגר.
        /// </summary>
        internal static string PRD13_PriceToAdult {
            get {
                return ResourceManager.GetString("PRD13_PriceToAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר לילד.
        /// </summary>
        internal static string PRD13_PriceToChild {
            get {
                return ResourceManager.GetString("PRD13_PriceToChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מוצר.
        /// </summary>
        internal static string PRD13_Prod {
            get {
                return ResourceManager.GetString("PRD13_Prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        internal static string PRD13_Select {
            get {
                return ResourceManager.GetString("PRD13_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחירת אורחים לארוחה.
        /// </summary>
        internal static string PRD13_SelectGuests {
            get {
                return ResourceManager.GetString("PRD13_SelectGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקטלוג לחץ כאן.
        /// </summary>
        internal static string RGS01_Catalog {
            get {
                return ResourceManager.GetString("RGS01_Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תעודת זהות.
        /// </summary>
        internal static string RGS01_ID {
            get {
                return ResourceManager.GetString("RGS01_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר עובד.
        /// </summary>
        internal static string RGS01_License {
            get {
                return ResourceManager.GetString("RGS01_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקה.
        /// </summary>
        internal static string RGS02_Clear {
            get {
                return ResourceManager.GetString("RGS02_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון נוסף.
        /// </summary>
        internal static string RGS03_AdditionalTelephone {
            get {
                return ResourceManager.GetString("RGS03_AdditionalTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך לידה.
        /// </summary>
        internal static string RGS03_BirthDate {
            get {
                return ResourceManager.GetString("RGS03_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום.
        /// </summary>
        internal static string RGS03_Day {
            get {
                return ResourceManager.GetString("RGS03_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחוז.
        /// </summary>
        internal static string RGS03_district {
            get {
                return ResourceManager.GetString("RGS03_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דוא&quot;ל.
        /// </summary>
        internal static string RGS03_Email {
            get {
                return ResourceManager.GetString("RGS03_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פקס.
        /// </summary>
        internal static string RGS03_Fax {
            get {
                return ResourceManager.GetString("RGS03_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם פרטי.
        /// </summary>
        internal static string RGS03_FirstName {
            get {
                return ResourceManager.GetString("RGS03_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to באנגלית.
        /// </summary>
        internal static string RGS03_Foreign {
            get {
                return ResourceManager.GetString("RGS03_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חיפה.
        /// </summary>
        internal static string RGS03_Haifa {
            get {
                return ResourceManager.GetString("RGS03_Haifa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בעברית.
        /// </summary>
        internal static string RGS03_Hebrew {
            get {
                return ResourceManager.GetString("RGS03_Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תעודת זהות.
        /// </summary>
        internal static string RGS03_ID {
            get {
                return ResourceManager.GetString("RGS03_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ירושלים.
        /// </summary>
        internal static string RGS03_Jerusalem {
            get {
                return ResourceManager.GetString("RGS03_Jerusalem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקום עבודה.
        /// </summary>
        internal static string RGS03_Job {
            get {
                return ResourceManager.GetString("RGS03_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפקיד.
        /// </summary>
        internal static string RGS03_Job_title {
            get {
                return ResourceManager.GetString("RGS03_Job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משפחה.
        /// </summary>
        internal static string RGS03_LastName {
            get {
                return ResourceManager.GetString("RGS03_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חודש.
        /// </summary>
        internal static string RGS03_Month {
            get {
                return ResourceManager.GetString("RGS03_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צפון.
        /// </summary>
        internal static string RGS03_North {
            get {
                return ResourceManager.GetString("RGS03_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר דרכון.
        /// </summary>
        internal static string RGS03_Passport {
            get {
                return ResourceManager.GetString("RGS03_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוקף דרכון.
        /// </summary>
        internal static string RGS03_PassportExp {
            get {
                return ResourceManager.GetString("RGS03_PassportExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        internal static string RGS03_Phone {
            get {
                return ResourceManager.GetString("RGS03_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדות חובה בטופס.
        /// </summary>
        internal static string RGS03_RequiredFields {
            get {
                return ResourceManager.GetString("RGS03_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        internal static string RGS03_Select {
            get {
                return ResourceManager.GetString("RGS03_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דרום.
        /// </summary>
        internal static string RGS03_South {
            get {
                return ResourceManager.GetString("RGS03_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תל אביב והמרכז.
        /// </summary>
        internal static string RGS03_TelAviv {
            get {
                return ResourceManager.GetString("RGS03_TelAviv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תואר.
        /// </summary>
        internal static string RGS03_Title {
            get {
                return ResourceManager.GetString("RGS03_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שנה.
        /// </summary>
        internal static string RGS03_Year {
            get {
                return ResourceManager.GetString("RGS03_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מלווה מספר.
        /// </summary>
        internal static string RGS04_AccNum {
            get {
                return ResourceManager.GetString("RGS04_AccNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף מלווה.
        /// </summary>
        internal static string RGS04_AddCom {
            get {
                return ResourceManager.GetString("RGS04_AddCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך לידה.
        /// </summary>
        internal static string RGS04_BirthDate {
            get {
                return ResourceManager.GetString("RGS04_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יום.
        /// </summary>
        internal static string RGS04_Day {
            get {
                return ResourceManager.GetString("RGS04_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        internal static string RGS04_Delete {
            get {
                return ResourceManager.GetString("RGS04_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם פרטי.
        /// </summary>
        internal static string RGS04_FirstName {
            get {
                return ResourceManager.GetString("RGS04_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משפחה.
        /// </summary>
        internal static string RGS04_LastName {
            get {
                return ResourceManager.GetString("RGS04_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חודש.
        /// </summary>
        internal static string RGS04_Month {
            get {
                return ResourceManager.GetString("RGS04_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוקף דרכון.
        /// </summary>
        internal static string RGS04_PassportExp {
            get {
                return ResourceManager.GetString("RGS04_PassportExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר דרכון.
        /// </summary>
        internal static string RGS04_passportNum {
            get {
                return ResourceManager.GetString("RGS04_passportNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        internal static string RGS04_Select {
            get {
                return ResourceManager.GetString("RGS04_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תואר.
        /// </summary>
        internal static string RGS04_Title {
            get {
                return ResourceManager.GetString("RGS04_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שנה.
        /// </summary>
        internal static string RGS04_Year {
            get {
                return ResourceManager.GetString("RGS04_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר דמי רישום ל.
        /// </summary>
        internal static string RGS05_Fees {
            get {
                return ResourceManager.GetString("RGS05_Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר.
        /// </summary>
        internal static string RGS05_Select {
            get {
                return ResourceManager.GetString("RGS05_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ ערך דמי רישום.
        /// </summary>
        internal static string RGS05_TotalRegistrationValue {
            get {
                return ResourceManager.GetString("RGS05_TotalRegistrationValue", resourceCulture);
            }
        }
    }
}
